### ISSUE TITLE
Ligatures not working correctly

### ISSUE THREAD

**Issue by iCraft85** [Moarram/headline#10]
So my ligatures are not working correctly, I am using kitty terminal and have setup Fira Code. Some of the ligatures do work but I am not 100% sure why the rest of em don't work.

This is how mine looks: 
<img width="208" alt="Screenshot 2021-12-12 at 9 17 36 PM" src="https://user-images.githubusercontent.com/58494292/145713902-e66000c2-eaee-47db-aef3-f585448fe187.png">

Is this due to my terminal? or did I like configure something wrong?

I am on MacOS Big Sur I don't think this changes anything but idk.

**Comment by Moarram** [comment]
I don't use Kitty so I can't give you a precise answer, but I have a few ideas:

* In Kitty the bold font can be configured independently from the normal font, so perhaps ligatures are only enabled for the non-bold characters right now?
* You could slightly decrease the spacing between characters since the underscores are only a pixel away from connecting.

**Comment by yorhodes** [comment]
I followed the instructions for iTerm2 and FiraCode Nerd Font and the ligatures still do not work correctly

<img width="270" alt="Screen Shot 2021-12-26 at 5 32 54 PM" src="https://user-images.githubusercontent.com/3020995/147421489-ccd7c666-86e4-4475-b9ea-2eb4c1c57c3c.png">

It's worth noting that the ligatures work correctly with the unpatched Fira Code (though the symbols obviously do not)
<img width="275" alt="Screen Shot 2021-12-26 at 5 33 31 PM" src="https://user-images.githubusercontent.com/3020995/147421493-39f09dfe-91b3-4e61-accc-583773ea6b5e.png">

**Comment by Moarram** [comment]
Glad you got it working!

**Comment by CouldBeThis** [comment]
I've had really inconsistent effects with this line but I can't figure out why it works sometimes and not others. Recently I installed on linux and with kitty terminal it wasn't working as expected. (I had likewise puzzling experience on Mac with iTerm previously.) I do notice that the line above `: ` and before the git status look to be drawing properly. `kitty.conf` followed by screenshot:

```conf
font_family       Fira Code  
```
![image](https://user-images.githubusercontent.com/53547181/155643500-82375a80-ccf5-4d6a-a822-10d88729c187.png)

If I remove the space from the name, it is as above except nothing is bolded:

```conf
font_family       FiraCode
## has same effect:
# font_family       FiraCode-Retina
```
![image](https://user-images.githubusercontent.com/53547181/155643900-121fd4da-0f25-4203-a0eb-e149dffdca46.png)

If I keep the space but use `Retina` variation, it is not quite perfect but with my eyesight I have to put my face right up to the screen to see the spaces between the lines:

```conf
font_family       Fira Code-Retina
```
![image](https://user-images.githubusercontent.com/53547181/155643298-a1782a91-06fe-476a-8137-4bec72da9a82.png)

Obviously you need this font available. 

I also saw in `kitty.conf` the settings for `symbol_map` which is supposed to allow you to specify which font to use for specific unicode characters. See [list of Unicode characters with codepoints](https://en.wikipedia.org/wiki/List_of_Unicode_characters). If you set for the underscore character, it works, *but* the whole line is unbolded, which actually I think it nicer because of being consistent instead of kind of dancing up and down. Moving and removing spaces and hyphens in the font names creates what seem to me to be completely unpredictable variations but the best combination I found is:

```conf
font_family       FiraCode
## assign font to _ underscore
symbol_map U+5F Fira Code-Retina
```
![image](https://user-images.githubusercontent.com/53547181/155645383-9284996c-7c40-494f-8376-ac3274308fbd.png)

I tried mapping `_` to PowerLineSymbols which is the example font used in `kitty.conf` docs; oddly this made the line completely disappear. 

Other `kitty` settings I noticed but did not thoroughly investigate were `font_features` and `box_drawing_scale`.

In the `kitty.conf` documentation there is also suggested a way to see what fonts you have on board and of those that have been mentioned, here is what my results were: 

```zsh
$ kitty + list-fonts 
Fira Code
    Fira Code Bold
    Fira Code Light
    Fira Code Medium
    Fira Code Regular
    Fira Code Retina
    Fira Code SemiBold
    FiraCode-Light
    FiraCode-Medium
    FiraCode-Regular
    FiraCode-Retina

PowerlineSymbols
    PowerlineSymbols
```

I did remove some duplicate lines for Fira Code whose presence I cannot explain; possibly I have more than one version or location of these and maybe that's what is causing the unpredictability. Also just to note that I was always seeing what would happen if I put in a fake font name to compare behaviour to what happens if you call a non existent font and all the screencaps above are *different* than that scenario, so it's never the case that the display is simply falling back to default. 

All this is just FYI in case someone else has issues; the question of font display in terminal seems to be pretty complicated.

**Comment by CouldBeThis** [comment]
Hey here is something weird. If you set the underscore to `U+2630 TRIGRAM FOR HEAVEN`:

```zsh
HEADLINE_LINE_CHAR='☰' # line above information   
```
you get this:

![image](https://user-images.githubusercontent.com/53547181/155651686-e349064d-e0eb-45fc-83fb-cdccf72ab257.png)

and same effect with `☃` (`U+2603 SNOWMAN`):

![image](https://user-images.githubusercontent.com/53547181/155654292-cc5bc038-b3f5-4743-baf8-a9718f4ac04f.png)

whereas if you use other full height characters, such as `🙾` (`U+1F67E CHECKER BOARD`) or any of ▇ ▒ ▓ ░, the size is consistent 

![image](https://user-images.githubusercontent.com/53547181/155653282-5d7a2f2c-fd08-42eb-b25d-f3649c92bb3e.png)


on the other hand, assigning it to the character `U+23BD HORIZONTAL SCAN LINE-9` (not underscore as default) makes the line join together perfectly rather than almostalmost like in my previous comment:

```zsh
HEADLINE_LINE_CHAR='⎽' # line above information
```
![image](https://user-images.githubusercontent.com/53547181/155652543-812d5b3e-0d53-49ef-abc6-4327a22e1128.png)

this all with `kitty.conf` set as previous:

```conf
font_family       FiraCode
## assign font to _ underscore
symbol_map U+5F Fira Code-Retina
```
