### ISSUE TITLE
Separator line show when open new terminal.

### ISSUE THREAD

**Issue by dev-dk35782** [Moarram/headline#17]
It also happens when clear screen and reload oh my zsh.

![image](https://user-images.githubusercontent.com/95513902/192224267-1b437187-1000-488a-bcc7-6e9a25d48a09.png)

I just install it. And I've never had that happen before.

**Comment by Moarram** [comment]
Yeah sorry about that... I recently changed the default behavior to always print the line because the auto feature isn't very robust. You'll need to set `HEADLINE_LINE_MODE='auto'` for the old behavior. See the [customization docs](https://github.com/Moarram/headline/blob/main/docs/Customization.md#separator-mode) for details.
