### ISSUE TITLE
Did I config wrong some properties? 

### ISSUE THREAD

**Issue by andqnguyen** [Moarram/headline#20]
Hi, I very like your theme. 
My terminal breaks a new line. Could you help me check this?

Have a nice day <3

![CleanShot 2022-12-23 at 09 40 06@2x](https://user-images.githubusercontent.com/116780628/209260097-1ec8db51-d9c1-42f0-90ca-56895829812c.png)

**Comment by andqnguyen** [comment]
<img width="383" alt="CleanShot 2022-12-23 at 09 43 14@2x" src="https://user-images.githubusercontent.com/116780628/209260370-e71952a4-707f-4ace-bead-02d38f064717.png">

**Comment by Moarram** [comment]
That's unusual. What terminal are you using?

It seems that your terminal considers the first 2 lines of the Headline prompt as part of the previous output (which is indeed the default). There's a setting in Headline that prints all 3 lines in the `$PROMPT` variable which should fix this. Be aware that it might cause other problems because most terminals expect `$PROMPT` to be only 1 line.
```shell
HEADLINE_INFO_MODE=prompt # print everything in the prompt
```

Additionally, it appears that your `$PROMPT` variable is getting a newline within it somehow. Does it only happen with Headline? Perhaps another prompt is interfering? Try printing the contents of `$PROMPT`. This is what I see with default settings:
```
$ echo $PROMPT
%(#.#.%(!.!.$))
```

**Comment by andqnguyen** [comment]
@Moarram Currently, I am using warp terminal
https://www.warp.dev/

**Comment by andqnguyen** [comment]
Thanks @Moarram  for your support. <3

**Comment by andqnguyen** [comment]
![CleanShot 2022-12-26 at 10 15 01](https://user-images.githubusercontent.com/116780628/209495322-f5f46ef3-cc8a-4db8-a6bf-8cac849a81d2.png)
`echo $PROMPT` return nothing in my terminal

**Comment by andqnguyen** [comment]
`Does it only happen with Headline? ` 
=> I use another theme, it works fine

**Comment by Moarram** [comment]
Okay I looked into Warp and I like it quite a bit. Unfortunately it [doesn't support multi-line prompts](https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts).

I tried making theme compatible but ran into other issues. The closest I can get requires reducing Headline to just the information line (no separator line or prompt character), and making the information line 1 character shorter than the terminal width because otherwise Warp inserts an unwanted newline.

However, there's a port of Headline for oh-my-posh ([wathhr/headline-omp](https://github.com/wathhr/headline-omp)) that you could try. This looks especially promising because oh-my-posh specializes in cross-terminal compatibility and already has [multi-line prompts working in Warp](https://github.com/warpdotdev/Warp/issues/1015#issuecomment-1342515004) (as of version 12.26.1).

**Comment by andqnguyen** [comment]
@Moarram  Thanks
