### ISSUE TITLE
Icons not displaying with Fira Code Nerd Font

### ISSUE THREAD

**Issue by AxelBuee** [Moarram/headline#6]
Hello @Moarram,

I'm currently on `Ubuntu 21.04`, using `Kitty` and I installed `Fira Code` font. However, I still don't see any icons on the line ...
![image](https://user-images.githubusercontent.com/17200960/141497263-1f0008dd-2fc8-43b1-a80c-e04a602b8f80.png)
I also tried `FiraCode Nerd Font` and `FiraCode Nerd Font Mono`  but then the ligatures stop working and I have neither a complete line nor icons.
![image](https://user-images.githubusercontent.com/17200960/141496962-b25a9676-3361-4681-b6e0-ad0755e8ffcd.png)

Do I need to enable something in a config file ? Because I don't see any icon related option in the theme file. I like this theme very much and with icons it would be perfect !

Please do not hesitate if you need more informations.
Axel

**Comment by Moarram** [comment]
It looks like Kitty has issues with Nerd Font icons because they aren't monospaced (see kovidgoyal/kitty#527). You could try using the "battle-tested" Meslo Nerd Font font that Powerlevel10k recommends (see https://github.com/romkatv/powerlevel10k#fonts). It describes how to install it for Kitty which is promising.

Once you have a working Nerd Font, you also need to specify your icons of choice by assigning to the prefix variables `HEADLINE_USER_PREFIX`, `HEADLINE_HOST_PREFIX`, `HEADLINE_PATH_PREFIX`, and `HEADLINE_BRANCH_PREFIX`.

**Comment by AxelBuee** [comment]
Thank you ! 
It is working great now with your indications :smile: 
![image](https://user-images.githubusercontent.com/17200960/141751124-1b024220-5935-4272-803b-467275f7e764.png)
